#### CraftSupport ####

demo-recipe:
    enabled: true

    item-name: '&a&lレシピデモ'
    material: 'DIAMOND'
    amount: 1
    lore:
        - 'Lore Line 1'
        - 'Lore Line 2'
        - 'Lore Line 3'
    enchantments:
        - 'DAMAGE_ALL:1'
        - 'DURABILITY:1'
    custom-model-data: 0
    shapeless: false
    shape:
        - 'AAA'
        - 'ABA'
        - 'AAA'
    ingredients:
        A: 'IRON_INGOT'
        B: 'DIAMOND'