#### CraftSupport ####

recipe:
    # デモレシピ
    demo-recipe:
        enabled: true
        item-name: '§a§lレシピデモ'
        material: 'DIAMOND'
        amount: 1
        lore:
            - 'Lore Line 1'
            - 'Lore Line 2'
            - 'Lore Line 3'
        enchantments:
            - 'DAMAGE_ALL:1'
            - 'DURABILITY:1'
        custom-model-data: 0
        # 固定レシピかどうか
        is-shaped: false
        # 何も入れない場所は半角スペースを入力
        shape:
            - ' A '
            - 'ABA'
            - ' A '
        ingredients:
            A: 'IRON_INGOT'
            B: 'DIAMOND'
