name: CraftSupporter
version: '${project.version}'
main: pro.freeserver.plugin.alphakun.craftsupporter.CraftSupporter
api-version: 1.18
authors: [ alpha9n ]
description: craftsupporter
website: https://freeserver.pro
